<? template('header.html'); ?>

<div style="display: flex; justify-content: center">
    <form style="width: 40%" class="ui form segment" action="/auth/login/" method="post">
        <div class="field">
            <label>First Name</label>
            <input type="text" name="login" placeholder="Login">
        </div>
        <div class="field">
            <label>Last Name</label>
            <input type="password" name="password" placeholder="Password">
        </div>
         <button class="ui button" type="submit">Submit</button>
    </form>
</div>

<? template('footer.html'); ?>